version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: quiz_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quiz_db
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: .
    container_name: quiz_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=quiz_db
      - JWT_SECRET_KEY=yoursecretkey
    depends_on:
      - db
