name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: docker build -t my-app .

    - name: Tag Image
      run: docker tag my-app:latest 142166253229.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest

    - name: Push to ECR
      run: docker push 142166253229.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest

    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 142166253229.dkr.ecr.ap-south-1.amazonaws.com
          docker pull 142166253229.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
          docker stop my-container || true
          docker rm my-container || true
          docker run -d -p 5000:5000 --name my-container 142166253229.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest