name: Deploy to AWS Auto Scaling

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configure AWS credentials
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-south-1

      # Authenticate Docker to ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 142166253229.dkr.ecr.ap-south-1.amazonaws.com

      # Build and push Docker image to ECR
      - name: Build and push Docker image
        run: |
          IMAGE_REPO=142166253229.dkr.ecr.ap-south-1.amazonaws.com/myimg
          docker build -t myimg .
          docker tag myimg:latest $IMAGE_REPO:latest
          docker push $IMAGE_REPO:latest

      # Refresh the Auto Scaling Group to deploy new image
      # - name: Refresh Auto Scaling Group
      #   run: |
      #     aws autoscaling start-instance-refresh \
      #       --auto-scaling-group-name myasg \
      #       --preferences MinHealthyPercentage=50 \
      #       --region ap-south-1